name: pub_dev_client
description: An open-source pub.dev client for searching and subscribing to packages
authors:
  - Jonathan White <jwhite@thinkdigital.software>
  - GroovinChip <groovinchip@gmail.com>
version: 0.6.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webfeed: ^0.4.2
  bloc: ^0.14.2
  flutter_bloc: ^0.15.1
  floating_search_bar: ^0.2.0
  groovin_material_icons: ^1.1.6
  pub_client:
      git: https://github.com/ThinkDigitalSoftware/pub_client.git
  flutter_markdown: ^0.2.0
  html2md: ^0.3.1
  #html2md:
  #    git: https://github.com/GroovinChip/html2md
  material_segmented_control: ^2.0.3
  cupertino_icons: ^0.1.2
  groovin_widgets: ^1.4.2
  provider: ^3.0.0+1
  url_launcher: ^5.0.3
  dynamic_theme: ^1.0.1
  package_info: ^0.4.0+4
  rounded_modal: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.5.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Regular.otf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
