name: pub_dev_client
description: An open-source pub.dev client for searching and subscribing to packages
authors:
  - Jonathan White <jwhite@thinkdigital.software>
version: 0.2.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webfeed: ^0.4.2
  bloc: ^0.14.2
  flutter_bloc: ^0.15.1
  floating_search_bar: ^0.2.0
  groovin_material_icons: ^1.1.6
  pub_client:
      git: https://github.com/ThinkDigitalSoftware/pub_client.git
  flutter_markdown: ^0.2.0
  html2md: ^0.3.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
